# Namespace for ArgoCD
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---

# Install ArgoCD
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
        - name: argocd-server
          image: argoproj/argocd:v2.0.3
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 443
              name: https

---

apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: argocd-server

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/your-username/your-repo.git
      type: git
      name: your-repo
      passwordSecret:
        key: password
        name: git-creds
      usernameSecret:
        key: username
        name: git-creds

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, admin, role:admin
    g, your-username, role:admin

---

apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: argocd
stringData:
  username: your-github-username
  password: your-github-token

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: note-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/your-repo.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: note-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

# Namespace for Note App
apiVersion: v1
kind: Namespace
metadata:
  name: note-app

---

# StatefulSet for PostgreSQL
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: note-app
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: notesdb
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: note-app
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres

---

# Deployment for Note App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app-deployment
  namespace: note-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-app
  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
      - name: note-app
        image: your-dockerhub-username/note-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: postgres.note-app.svc.cluster.local
        - name: DATABASE_NAME
          value: notesdb
        - name: DATABASE_USER
          value: user
        - name: DATABASE_PASSWORD
          value: password

---

apiVersion: v1
kind: Service
metadata:
  name: note-app-service
  namespace: note-app
spec:
  selector:
    app: note-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---

# Ingress for Note App
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: note-app-ingress
  namespace: note-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: note-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: note-app-service
            port:
              number: 80

---

# PersistentVolume for PostgreSQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: note-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/postgres

---

# PersistentVolumeClaim for PostgreSQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: note-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
